services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ALLOW_ANONYMOUS_LOGIN: yes
        ports:
            - "2181:2181"

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9093:9093"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
            KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
            KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
            KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT

    notification-service:
        build: .
        container_name: notification-service
        ports:
            - "8080:8080"
        depends_on:
            - kafka
        environment:
            - KAFKA_BROKER=kafka:9092
