DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL 
);

CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    projectName VARCHAR(150) NOT NULL,
    projectOwner int NOT NULL,
    FOREIGN KEY (projectOwner) REFERENCES users(id) ON DELETE CASCADE
);